ensemble: null
feat:
  params:
    batch_size: 128
    n_jobs: 4
    normalize_targets: true
  type: ChemPropFeaturizer
model:
  freeze_weights: null
  param_path: null
  params:
    batch_norm: true
    depth: 4
    dropout: 0.2
    ffn_hidden_dim: 1024
    ffn_hidden_num_layers: 4
    from_chemeleon: true
    n_tasks: 1
  serial_path: null
  type: ChemPropModel
split:
  params:
    random_state: 42
    test_size: 0
    train_size: 1.0
    val_size: 0
  type: ShuffleSplitter
train:
  params:
    accelerator: gpu
    early_stopping: true
    early_stopping_min_delta: 0.001
    early_stopping_mode: min
    early_stopping_patience: 10
    max_epochs: 50
    monitor_metric: val_loss
    use_wandb: false
    wandb_project: demos
  type: LightningTrainer
transform: null
